# Generated by Django 5.1.2 on 2024-10-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام غذا')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('rate', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('price', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name='زمان لازم')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('photo', models.ImageField(upload_to='foods/', verbose_name='تصویر محصول')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
                'db_table': 'foods',
            },
        ),
    ]
