# Generated by Django 5.1.2 on 2024-10-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
