# Generated by Django 5.1.2 on 2024-10-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(default=0, verbose_name='زمان لازم'),
        ),
    ]
