# Generated by Django 5.1.2 on 2024-11-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FOOD_TYPE', models.ManyToManyField(to='foods.food', verbose_name='FOODTYPE')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Food', to='foods.food', verbose_name='food')),
            ],
            options={
                'verbose_name': 'FOOD_TYPE',
                'verbose_name_plural': 'FOOD_TYPES',
                'db_table': 'FOOD_TYPE',
            },
        ),
    ]
