# Generated by Django 5.1.2 on 2024-11-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('Breakfast', 'صبحانه'), ('Lunch', 'ناهار'), ('Dinner', 'شام'), ('Drink', 'نوشیدنی'), ('Dessert', 'دسر')], default='Lunch', max_length=10, verbose_name='نوع غذا'),
        ),
        migrations.DeleteModel(
            name='Food_Type',
        ),
    ]
