# Generated by Django 5.1.2 on 2024-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_food_type_food_delete_food_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام نوع غذا')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='type_food',
        ),
        migrations.AddField(
            model_name='food',
            name='types',
            field=models.ManyToManyField(to='foods.foodtype', verbose_name='نوع غذا'),
        ),
    ]
