# Generated by Django 5.1.2 on 2024-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='شماره تماس')),
                ('ReservationDay', models.DateField(verbose_name='روز رزرو')),
                ('ReservationTime', models.TimeField(verbose_name='ساعت رزرو')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'db_table': 'reservation',
            },
        ),
    ]
