# Generated by Django 5.1.2 on 2024-11-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='CountOfPerson',
            field=models.IntegerField(default=2, verbose_name='تعداد افراد'),
        ),
    ]
